apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf:
    pid /tmp/nginx.pid;

    events {
        worker_connections 128;
    }

    http {
        include /etc/nginx/mime.types;
        fastcgi_temp_path /tmp/fastcgi_temp;
        uwsgi_temp_path /tmp/uwsgi_temp;
        proxy_temp_path /tmp/proxy_temp;
        scgi_temp_path /tmp/scgi_temp;
        client_body_temp_path /tmp/client_body;

        server {
            listen 8000; 
            root /var/www/html; 

            location / {
                autoindex on;
            }

            location = /basic_status {
                stub_status;
            }
        }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html
data:
  index.html: |
    <h1> hello all !!! </h1>