apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  namespaceSelector:
    any: true
  endpoints:
  - port: port-metrics
    path: '/metrics'