server:
  standalone:
    enabled: false
    
  ha:
      enabled: true
      replicas: 1
      config: |
        disable_mlock = true
        ui = true
        cluster_addr = "https://POD_IP:8201"

        listener "tcp" {
          tls_disable = 1
          address = "[::]:8200"
          cluster_address = "[::]:8201"
        }
        storage "consul" {
          path = "vault"
          address = "HOST_IP:8500"
        }
        
  ui:
    enabled: true
    serviceType: "ClusterIP"