apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-hipster
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: hipster-shop-tls-cert
  rules:
  - host:  {{ .Values.ingress.host }}
    http:
      paths:
      - backend:
          serviceName: frontend
          servicePort: {{ .Values.service.port }}